@startuml
[*] --> State1
State1 --> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted / RetryX
State3 --> [*] : Succeeded / SaveResultX
State3 --> [*] : Aborted [MaxCheckX]
State3 --> State3 : Failed
@enduml
